"""SwinV2 window-based multi-head self-attention with cosine attention
and continuous position bias (L2).

Cosine attention: Q/K are L2-normalized, scaled by a learnable per-head
logit_scale, then biased with a continuous relative position bias (CPB)
generated by a small MLP from log-spaced relative coordinates.

Reference: timm/models/swin_transformer_v2.py WindowAttention
"""

from __future__ import annotations

import math
from typing import Optional, Tuple

import torch
import torch.nn as nn
import torch.nn.functional as F

from ..L1.linear import Linear
from ..L1.softmax import Softmax


class SwinV2WindowAttention(nn.Module):
    """Window-based multi-head self-attention with cosine attention and CPB.

    Args:
        dim: Number of input channels.
        window_size: Window size (height, width).
        num_heads: Number of attention heads.
        qkv_bias: If True, add learnable bias to Q and V (K bias is zero).
        attn_drop: Dropout ratio on attention weights.
        proj_drop: Dropout ratio on output projection.
        pretrained_window_size: Window size used during pretraining (for CPB
            coordinate normalization). (0, 0) means use current window_size.
    """

    def __init__(
        self,
        dim: int,
        window_size: Tuple[int, int],
        num_heads: int,
        qkv_bias: bool = True,
        attn_drop: float = 0.0,
        proj_drop: float = 0.0,
        pretrained_window_size: Tuple[int, int] = (0, 0),
    ):
        super().__init__()
        self.dim = dim
        self.window_size = window_size
        self.pretrained_window_size = pretrained_window_size
        self.num_heads = num_heads

        self.logit_scale = nn.Parameter(torch.full((num_heads, 1, 1), math.log(10)))

        # CPB MLP: 2 -> 512 -> num_heads
        self.cpb_mlp = nn.Sequential(
            Linear(2, 512, bias=True),
            nn.ReLU(inplace=True),
            Linear(512, num_heads, bias=False),
        )

        self.qkv = Linear(dim, dim * 3, bias=False)
        if qkv_bias:
            self.q_bias = nn.Parameter(torch.zeros(dim))
            self.register_buffer("k_bias", torch.zeros(dim), persistent=False)
            self.v_bias = nn.Parameter(torch.zeros(dim))
        else:
            self.q_bias = None
            self.k_bias = None
            self.v_bias = None

        self.attn_drop = nn.Dropout(attn_drop)
        self.proj = Linear(dim, dim, bias=True)
        self.proj_drop = nn.Dropout(proj_drop) if proj_drop > 0.0 else nn.Identity()
        self.softmax = Softmax(dim=-1)

        win_h, win_w = self.window_size
        self.register_buffer(
            "relative_coords_table",
            torch.zeros(1, 2 * win_h - 1, 2 * win_w - 1, 2),
            persistent=False,
        )
        self.register_buffer(
            "relative_position_index",
            torch.zeros(win_h * win_w, win_h * win_w, dtype=torch.long),
            persistent=False,
        )
        self._init_buffers()

    def _init_buffers(self) -> None:
        """Compute relative coords table and position index."""
        if self.k_bias is not None:
            self.k_bias.zero_()
        table, index = self._make_pair_wise_relative_positions()
        self.relative_coords_table.copy_(table)
        self.relative_position_index.copy_(index)

    def _make_pair_wise_relative_positions(self) -> Tuple[torch.Tensor, torch.Tensor]:
        win_h, win_w = self.window_size

        coords_h = torch.arange(-(win_h - 1), win_h, dtype=torch.float32)
        coords_w = torch.arange(-(win_w - 1), win_w, dtype=torch.float32)
        table = torch.stack(torch.meshgrid(coords_h, coords_w, indexing="ij"))
        table = table.permute(1, 2, 0).contiguous().unsqueeze(0)

        if self.pretrained_window_size[0] > 0:
            table[:, :, :, 0] /= self.pretrained_window_size[0] - 1
            table[:, :, :, 1] /= self.pretrained_window_size[1] - 1
        else:
            table[:, :, :, 0] /= win_h - 1
            table[:, :, :, 1] /= win_w - 1
        table *= 8
        table = torch.sign(table) * torch.log2(torch.abs(table) + 1.0) / math.log2(8)

        ch = torch.arange(win_h, dtype=torch.long)
        cw = torch.arange(win_w, dtype=torch.long)
        coords = torch.stack(torch.meshgrid(ch, cw, indexing="ij"))
        coords_flat = torch.flatten(coords, 1)
        rel = coords_flat[:, :, None] - coords_flat[:, None, :]
        rel = rel.permute(1, 2, 0).contiguous()
        rel[:, :, 0] += win_h - 1
        rel[:, :, 1] += win_w - 1
        rel[:, :, 0] *= 2 * win_w - 1
        index = rel.sum(-1)

        return table, index

    def forward(
        self,
        x: torch.Tensor,
        mask: Optional[torch.Tensor] = None,
    ) -> torch.Tensor:
        """
        Args:
            x: (num_windows*B, N, C)
            mask: (num_windows, Wh*Ww, Wh*Ww) or None

        Returns:
            (num_windows*B, N, C)
        """
        B_, N, C = x.shape

        if self.q_bias is not None:
            qkv_bias = torch.cat((self.q_bias, self.k_bias, self.v_bias))
            qkv = F.linear(x, self.qkv.weight, qkv_bias)
        else:
            qkv = self.qkv(x)
        qkv = qkv.reshape(B_, N, 3, self.num_heads, -1).permute(2, 0, 3, 1, 4)
        q, k, v = qkv.unbind(0)

        attn = F.normalize(q, dim=-1) @ F.normalize(k, dim=-1).transpose(-2, -1)
        logit_scale = torch.clamp(self.logit_scale, max=math.log(1.0 / 0.01)).exp()
        attn = attn * logit_scale

        bias_table = self.cpb_mlp(self.relative_coords_table).view(-1, self.num_heads)
        bias = bias_table[self.relative_position_index.view(-1)].view(
            self.window_size[0] * self.window_size[1],
            self.window_size[0] * self.window_size[1],
            -1,
        )
        bias = bias.permute(2, 0, 1).contiguous()
        bias = 16 * torch.sigmoid(bias)
        attn = attn + bias.unsqueeze(0)

        if mask is not None:
            num_win = mask.shape[0]
            attn = attn.view(-1, num_win, self.num_heads, N, N) + mask.unsqueeze(1).unsqueeze(0)
            attn = attn.view(-1, self.num_heads, N, N)

        attn = self.softmax(attn)
        attn = self.attn_drop(attn)

        x = (attn @ v).transpose(1, 2).reshape(B_, N, C)
        x = self.proj(x)
        x = self.proj_drop(x)
        return x
